### ISSUE TITLE
Cannot import add_statistical_test_annotation

### ISSUE THREAD

**Issue by FritzDonaldHansen** [webermarcolivier/statannot#14]
Hi, 
I am kind of stuck trying to fix this error. Perhaps it's an implementing issue, though it doesn't have a problem just importing the module statannot. Also I noticed in statannot.py the function is called differently (add_stat_annotation // not add_statistical_test_annotation), though several blogs from late 2018 recommended latter function name. This is my code:

from statannot import add_statistical_test_annotation
(...)
    with sns.axes_style(style='ticks'):
        g = sns.catplot("Category", "Week 2", data=df, kind="box")
        g.set_axis_labels("Category", str(input_parameter))
        add_statistical_test_annotation(g, df, [("SHAM", "iCMP"), ("PBS", "iCMP"), ("eGFP", "iCMP")],
                                        test='Mann-Whitney', order=None, textFormat='star', loc='inside', verbose=2)
        plt.show()

Error:  
from statannot import add_statistical_test_annotation
ImportError: cannot import name 'add_statistical_test_annotation'

Any help gladly appreciated!

**Comment by MJuanchich** [comment]
I have the same issue, have you found a solution?
