### ISSUE TITLE
small suggestions

### ISSUE THREAD

**Issue by timodonnell** [webermarcolivier/statannot#15]
Thanks for such a useful package! A couple quick ideas in case you have time to make any changes.

* Would be useful to have a way to pass `equal_var=False` to `scipy.stats.ttest_ind` for a Welch's test. This could also just be made to be the default, as it is usually a better choice than a standard t test that assumes equal variance, see e.g. [here](https://osf.io/sbp6k/) for one reference.
* I think annotations like "p < xxx", where xxx is an exact calculated p value, should probably be changed to "p = xxx".
* Ability to write p values using a provided format string like "%0.2f" so the label can read "p = 0.02" instead of "2.0e-2"

**Comment by webermarcolivier** [comment]
Thanks for the suggestions. I added the Welch's t-test for comparing samples with different variances and made it as default, and also an argument to format the p-value on the annotation.
