### ISSUE TITLE
Remove ns p-value lines

### ISSUE THREAD

**Issue by mizraelson** [webermarcolivier/statannot#25]
Hi) Is there a way to remove NS p-values so there are no lines and values for non-significant pairs?
Thank you)

**Comment by webermarcolivier** [comment]
You could just remove the pair from the input list.

If you mean an option to hide non-significant pairs, this would lie out of the framework of this tool which allows to perform a few comparisons of means between sample pairs. Something like computing all possible pairwise comparisons and selecting only significant differences would have to be handled in a multiple test framework, like ANOVA, or multiple test corrections.

**Comment by mizraelson** [comment]
No, the question was actually easier and I have added this option by myself. What I wanted is not to hide pairs of samples but to hide NS p-values.
The question I have right now is there a way to apply your function to Facet Grid.

**Comment by webermarcolivier** [comment]
About your question, if you want to hide only the text label of non-significant pairs, but still draw the line, you can do it by changing the list of pvalue annotation labels, as follows (with an empty label for p > 0.05):
```python
pvalue_thresholds=[[1e-4, "****"], [1e-3, "***"], [1e-2, "**"], [0.05, "*"], [1, ""]]
```

**Comment by mizraelson** [comment]
I know)) But I have added a way to hide the line as well.  I have added:
if no_ns and pval>0.05:
                continue
So the cycle stops without further actions if pval is ns.

**Comment by webermarcolivier** [comment]
Ok, I'll consider implementing it as an option.

**Comment by mizraelson** [comment]
> @mizraelson, can you tell where did you added the if statement?
@YiJessePi  here is the context:

       if valid:
            # Get position of boxes
            x1 = find_x_position_box(box_plotter, box1)
            x2 = find_x_position_box(box_plotter, box2)
            box_data1 = get_box_data(box_plotter, box1)
            box_data2 = get_box_data(box_plotter, box2)
            ymax1 = box_data1.max()
            ymax2 = box_data2.max()

            pval, formatted_output, test_short_name = stat_test(box_data1, box_data2, test, **stats_params)
            test_result_list.append({'pvalue': pval, 'test_short_name': test_short_name,
                                     'formatted_output': formatted_output, 'box1': box1,
                                     'box2': box2})
            if no_ns and pval>0.05:
                continue
                
            if verbose >= 1:
                print("{} v.s. {}: {}".format(label1, label2, formatted_output))

            if text_format == 'full':

**Comment by webermarcolivier** [comment]
About your original question, if you also hide the line (i.e. hiding the annotation of the test) then you in practice hiding all statistical tests that resulted in a non-significant p-value. Deciding which tests are significant should be handled in the framework of multiple test correction.
