### ISSUE TITLE
No multiple testing correction for significance

### ISSUE THREAD

**Issue by kennethv93** [webermarcolivier/statannot#29]
The pairwise testing happens without any correction for significance like with Bonferroni correction for example. A test might show up as significant while it might be not significant if correction were to be applied. Is it possible to add this feature?

**Comment by agamemnonc** [comment]
Could you not just manually adjust the `pvalue_thresholds` parameter if you want Bonferroni correction? Bear in mind, `scipy` does not support multiple comparison correction out of the box so there is no way to pass in this information in the statistical test. 

In my opinion, multiple comparison correction should not implemented in this toolkit; this is just a visualisation toolkit, not a statistical comparison library.

**Comment by kennethv93** [comment]
The pairwise testing is already in it but without the correction so this toolkit is already for statistical comparison. If it were pure for visualisation, there would be the option to just give the p-values instead of the toolkit calculating them. This would maybe be the better option to make it for pure visualisation!

**Comment by webermarcolivier** [comment]
I agree that the safest way would be to restrict this toolkit to pure visualization, and require the user to perform the tests and input the p-values by himself. By safe I mean avoiding bad interpretation of statistical tests, such as performing many tests and only displaying the pairs with a p-value below a threshold. This is one of the reason why I did not implement the requested feature to remove the visible annotation for non-significant pairs (issue #25). This would probably lead to a misuse as for example running the tests on all possible pairs and only displaying p-value below the threshold, without any multiple test correction.

However, completely separating the statistical tests from the toolkit would lead to a great decrease in usability. There is a demand for such a toolkit that integrates both statistical tests and visualization linked to visualizations of the seaborn package.

The alternative would be to require the user to perform the tests, clearly limiting the scope of the toolkit to visualization only.

Any opinion and contribution welcomed.

**Comment by agamemnonc** [comment]
Personally, I would opt for the latter; i.e., limit the scope of this toolkit to visualisation. 

If not, then definitely support the option to use it purely for visualisation (as per #28).

One obvious advantage is that the toolkit won't need updated every time that a new feature is added/modified in `scipy.stats`. Supporting every single statistical function in `stats` can result in most of the code essentially being a binding library. For example, `kruskal` is not currently supported and the user either has to modify the code (which many people won't bother) or they cannot use the library until this feature is included. 

Another reason (and a completely personal opinion here) is that it might not be safe to completely disassociate the user from the statistical tests. For example, it might be tempting for someone who doesn't really know what they are doing to use this library with defaults and not really check what's happening under the hood and beyond the produced significance stars.

**Comment by webermarcolivier** [comment]
I went the middle way and implemented the option to input custom p-values.

Any feedback welcomed.

**Comment by webermarcolivier** [comment]
See latest commit acc346ff172711b1574ff855a2c478f55010841b , where the implementation has been corrected.

**Comment by agamemnonc** [comment]
Cool, I can have a look in the next couple of days and give some feedback.

**Comment by agamemnonc** [comment]
I just had a look and go at this and it LGTM.

One minor suggestion:

docstring 
```
:param pvalues: list of p-values for each box pair comparison.
```

-->

```
:param pvalues: list or array of p-values for each box pair comparison.
```

**Comment by kennethv93** [comment]
Oh waw, what a coincidence haha. I just tested it with the p-values. Works great for me, great addition! Thanks @webermarcolivier

**Comment by webermarcolivier** [comment]
Great, thanks for the feedback!
