### ISSUE TITLE
Calculate annotation for hue-ed plots

### ISSUE THREAD

**Issue by mmagnus** [webermarcolivier/statannot#3]
Hey, do you think it would be possible to apply the library to plots when you hue-ed values?

![screen shot 2018-11-08 at 10 31 02 am](https://user-images.githubusercontent.com/118740/48189874-79c2f780-e341-11e8-9732-c9eff529ba4a.png)

https://seaborn.pydata.org/generated/seaborn.boxplot.html?highlight=boxplot#seaborn.boxplot

**Comment by webermarcolivier** [comment]
Yes, I am working on it, although this will lead to a strong dependency on seaborn package.

**Comment by mmagnus** [comment]
Wow, awesome. Let me know if you need any help :-)
