### ISSUE TITLE
Line lengths do not match non-default boxplot width values

### ISSUE THREAD

**Issue by agamemnonc** [webermarcolivier/statannot#35]
Using the source code that produced this example [figure](https://raw.githubusercontent.com/webermarcolivier/statannot/master/example/example_hue_pairs.png) but altering the boxplot width:

```python
ax = sns.boxplot(data=df, x=x, y=y, hue=hue, width=0.25)
```

results in this:
![image](https://user-images.githubusercontent.com/7148165/69884275-7f360b80-12cf-11ea-9a82-275a8ecc7b0c.png)

It would be nice if the lines were aligned to the boxplot centers even for non-default width values. 
(Obviously this is an extreme case where lines would be become too small, but this issue also holds for simper cases, e.g. 2 x 2 comparisons).

**Comment by webermarcolivier** [comment]
Thanks for the bug reporting. The `width` argument simply needed to be correctly passed to seaborn `boxplotter` method. Note that in the case of non-default width, you need to pass the same argument value to both seaborn `boxplot` and `add_stat_annotation` functions. I also added this argument in the example notebook.
