### ISSUE TITLE
plot created without annotation - error message "add_stat_annotation() got an unexpected keyword argument 'box_pairs'"

### ISSUE THREAD

**Issue by MJuanchich** [webermarcolivier/statannot#36]
I try to run a simple plot with the annotation but do not manage to make it work. I have checked that my packages are up to date:
(I use Anaconda and Spyder)
sns: '0.9.0'
numpy: '1.15.4'
matplotlib:  '3.0.2'
pd: 0.23.4
scipy: '1.1.0'

My code produces the right figure but without annotation and spits the following error message: 
TypeError: add_stat_annotation() got an unexpected keyword argument 'box_pairs'

Any idea why? Any help much appreciated!

Marie

The code I use :

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from statannot import add_stat_annotation
from pandas.compat import StringIO

df = sns.load_dataset("tips")
from statannot.statannot import add_stat_annotation

x = "day"
y = "total_bill"
order = ['Sun', 'Thur', 'Fri', 'Sat']
ax = sns.boxplot(data=df, x=x, y=y, order=order)
test_results = add_stat_annotation(ax, data=df, x=x, y=y, order=order,
                                   box_pairs=[("Thur", "Fri"), ("Thur", "Sat"), ("Fri", "Sun")],
                                   test='Mann-Whitney', text_format='star', loc='outside', verbose=2)
plt.savefig('example_non-hue_outside.png', dpi=300, bbox_inches='tight')
test_results`

**Comment by webermarcolivier** [comment]
You have two different imports in your code, the correct one is
```python
from statannot import add_stat_annotation
```
Could you try to remove the line
```python
from statannot.statannot import add_stat_annotation
```
?

**Comment by MJuanchich** [comment]
Hi thank you for looking into this!

I have amended that line but still have the same error. I do not have any error messages when I load the package (using from statannot import add_stat_annotation), only when I run the figure where I want to see the annotations.

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from statannot import add_stat_annotation
from pandas.compat import StringIO

sns.set(style="whitegrid")


df = sns.load_dataset("tips")

x = "day"
y = "total_bill"
order = ['Sun', 'Thur', 'Fri', 'Sat']
ax = sns.boxplot(data=df, x=x, y=y, order=order)
test_results = add_stat_annotation(ax, data=df, x=x, y=y, order=order,
                                   box_pairs=[("Thur", "Fri"), ("Thur", "Sat"), ("Fri", "Sun")],
                                   test='Mann-Whitney', text_format='star', loc='outside', verbose=2)
plt.savefig('example_non-hue_outside.png', dpi=300, bbox_inches='tight')
test_results

![image](https://user-images.githubusercontent.com/49307923/70248472-dbd37380-1772-11ea-8ef0-ecff126da941.png)

**Comment by webermarcolivier** [comment]
You'got an old version of the package, please update to the latest version with
```
pip install --upgrade git+git://github.com/webermarcolivier/statannot.git
```

**Comment by MJuanchich** [comment]
Hi Marc-Olivier, I tried that but still not working. I had the latest package installed (but still updated it) and still have the same error message. Happy to send a more detailed version of what the command "says" when I run the update.

![image](https://user-images.githubusercontent.com/49307923/70517399-75fb3900-1b30-11ea-85d0-306f5f0ba97e.png)


Marie

**Comment by webermarcolivier** [comment]
Could you try to print in your jupyter notebook session the description of the function?
```python
import statannot
help(statannot.add_stat_annotation)
```

**Comment by MJuanchich** [comment]
Thanks for bearing with me and trying to find a solution ! Here is what I get when I run the above.

Help on function add_stat_annotation in module statannot.statannot:

add_stat_annotation(ax, data=None, x=None, y=None, hue=None, order=None, hue_order=None, box_pairs=None, width=0.8, perform_stat_test=True, pvalues=None, test_short_name=None, test=None, text_format='star', pvalue_format_string=<object object at 0x000001F941F7A7B0>, text_annot_custom=None, loc='inside', show_test_name=True, pvalue_thresholds=<object object at 0x000001F941F7A7B0>, stats_params={}, use_fixed_offset=False, line_offset_to_box=None, line_offset=None, line_height=0.02, text_offset=1, color='0.2', linewidth=1.5, fontsize='medium', verbose=1)
    Optionally computes statistical test between pairs of data series, and add statistical annotation on top
    of the boxes. Uses the same exact arguments `data`, `x`, `y`, `hue`, `order`,
    `hue_order` as the seaborn boxplot function.
    
    This function works in one of the two following modes:
    a) `perform_stat_test` is True: statistical test as given by argument `test` is performed.
    b) `perform_stat_test` is False: no statistical test is performed, list of custom p-values `pvalues` are
       used for each pair of boxes. The `test_short_name` argument is then used as the name of the
       custom statistical test.
    
    :param line_height: in axes fraction coordinates
    :param text_offset: in points
    :param box_pairs: can be of either form: For non-grouped boxplot: `[(cat1, cat2), (cat3, cat4)]`. For boxplot grouped by hue: `[((cat1, hue1), (cat2, hue2)), ((cat3, hue3), (cat4, hue4))]`
    :param pvalue_format_string: defaults to `"{.3e}"`
    :param pvalue_thresholds: list of lists, or tuples. Default is: For "star" text_format: `[[1e-4, "****"], [1e-3, "***"], [1e-2, "**"], [0.05, "*"], [1, "ns"]]`. For "simple" text_format : `[[1e-5, "1e-5"], [1e-4, "1e-4"], [1e-3, "0.001"], [1e-2, "0.01"]]`
    :param pvalues: list or array of p-values for each box pair comparison.

**Comment by webermarcolivier** [comment]
Then the first error message you got about the `box_pairs` argument does not make sense...
Please try again running the following minimal code in a new session:
```python
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from statannot import add_stat_annotation

df = sns.load_dataset("tips")
x = "day"
y = "total_bill"
order = ['Sun', 'Thur', 'Fri', 'Sat']
ax = sns.boxplot(data=df, x=x, y=y, order=order)
test_results = add_stat_annotation(ax, data=df, x=x, y=y, order=order,
                                   box_pairs=[("Thur", "Fri"), ("Thur", "Sat"), ("Fri", "Sun")],
                                   test='Mann-Whitney', text_format='star', loc='outside', verbose=2)
```

**Comment by MJuanchich** [comment]
That works!!

Why do you think the previous version did not?

Marie
