### ISSUE TITLE
Bug with violinplot + ax.set_yscale(log)?

### ISSUE THREAD

**Issue by alyosha-f** [webermarcolivier/statannot#39]
I have called

```
fig, ax = plt.subplots(...)
sns.violinplot(ax=ax[0], ...)
add_stat_annotation(ax[0], ...)
ax[0].set_yscale("log")
```

For both `loc='inside'` and `'outside'`, I get very wrong limits on the y-axis. The limits can still be set manually with `ax.set_ylim(...)`, and then everything is fine again. If I skip the `set_yscale`, everything works fine

Is this behaviour expected?

**Comment by webermarcolivier** [comment]
Setting the log scale before calling the `add_stat_annotation` should work fine. Also, you can tweak the distance between the first annotation line and the top of the box/violin with the `line_offset_to_box` parameter.
```python
df = sns.load_dataset("tips")
x = "day"
y = "total_bill"
order = ['Sun', 'Thur', 'Fri', 'Sat']
df[y] = df[y] + 10
ax = sns.violinplot(data=df, x=x, y=y, order=order)
ax.set_yscale('log')
test_results = add_stat_annotation(ax, data=df, x=x, y=y, order=order,
                                   box_pairs=[("Thur", "Fri"), ("Thur", "Sat"), ("Fri", "Sun")],
                                   test='Mann-Whitney', text_format='star', loc='inside',
                                   line_offset_to_box=0.15,
                                   verbose=2)
```
However, I would check if the implementation of the seaborn violinplot is indeed compatible with a log scale axis. Usually, one would want to compute the log(values) before plotting, such that the kernel density estimate (the smooth distribution) can be computed correctly.

**Comment by alyosha-f** [comment]
I confirm, doing `set_yscale("log")` before `add_stat_annotation` fixes the problem. Thanks for the quick reply
