### ISSUE TITLE
Multiple comparisons

### ISSUE THREAD

**Issue by cimbi** [webermarcolivier/statannot#40]
Is the multiple comparisons problem tackled somehow in the library? If not, adding an option to take this into account would be great. I am happy to help with that if needed.

**Comment by webermarcolivier** [comment]
In the current library there is no correction for multiple comparisons, but yes, it would be a very good idea to implement it. Ideally either Bonferroni or Benjamini-Hochberg.

In the case of Bonferroni, we could compute the corrected p-values, and use the same star-annotation system.

In the case of BH, however, there is strictly speaking no corrected p-values, but rather pairs that are significantly different given the family-wise false discovery rate (FDR). I am not sure how to show this on the annotation.

Any suggestions welcomed.

**Comment by cimbi** [comment]
I'd do Bonferroni since it is really easy to implement. As for BH - not sure about that. There could perhaps be a table attached to the plot axes? I think if we used annotations for this the plot would be too cluttered.

**Comment by efharkin** [comment]
I added this feature in a pull request here: https://github.com/webermarcolivier/statannot/pull/41.

**Comment by webermarcolivier** [comment]
Pulled request #41 has been merged. Thanks to @efharkin for the implementation. For the moment, only Bonferroni has been implemented, so I keep this issue open.

**Comment by JohannesWiesner** [comment]
BH correction would be a very nice addition!

**Comment by DarthTrevis** [comment]
I just updated my PR #44 about this, please tell me if the result of the implementation matches the expectations or if you would see it differently.
