### ISSUE TITLE
All Nan slice encountered when df had no nans

### ISSUE THREAD

**Issue by wylhtydtm** [webermarcolivier/statannot#47]
Hi,

My data frame input has no nans, but it still raised the error nanargmax. How do I resolve this error? Thank you very much

  File "<ipython-input-213-2e07b097a81a>", line 54, in <module>
    test='t-test_paired', text_format='full', loc='inside', verbose=2)

  File "/anaconda3/lib/python3.6/site-packages/statannot/statannot.py", line 519, in add_stat_annotation
    (y_stack_arr[0, :] <= x2))])

  File "<__array_function__ internals>", line 6, in nanargmax

  File "/anaconda3/lib/python3.6/site-packages/numpy/lib/nanfunctions.py", line 551, in nanargmax
    raise ValueError("All-NaN slice encountered")

ValueError: All-NaN slice encountered

**Comment by DarthTrevis** [comment]
Hi @wylhtydtm,
Could you maybe show the code calling the seaborn plotting function and `add_stat_annot` ?
(a minimal non-working example of dataset generating this error may also be needed later)

**Comment by wylhtydtm** [comment]
> Hi @wylhtydtm,
> Could you maybe show the code calling the seaborn plotting function and `add_stat_annot` ?
> (a minimal non-working example of dataset generating this error may also be needed later)

Thank you so much for your reply. My df contains columns representing 2000+features and rows with different objects recorded from 'window_id' 0-8( thus appending one object (9 rows) to another by rows). I am trying to plot window_id against each feature and calculate the statistical significance between window_ids.

Here is my code:


plt.close('all')

feats_toplot = ['speed_90th',
                'speed_10th',
                'ang_vel_midbody_abs_90th',
                'd_speed_90th',
                'd_speed_10th',
                'd_ang_vel_midbody_abs_90th',
                'speed_w_forward_90th',
                'speed_w_forward_10th',
                'speed_head_tip_w_forward_90th',
                'speed_head_base_w_forward_90th',
                'speed_tail_base_w_forward_90th',
                'speed_head_tip_w_backward_90th',
                'speed_head_base_w_backward_90th',
                'speed_tail_base_w_backward_90th',
                'quirkiness_50th',
                'width_midbody_50th',
                'motion_mode_paused_frequency',
                'motion_mode_paused_fraction',
                'motion_mode_forward_frequency',
                'motion_mode_forward_fraction',
                'motion_mode_backward_frequency',
                'motion_mode_backward_fraction',
                'curvature_mean_neck_abs_90th',
                'curvature_mean_midbody_abs_90th',
                'd_curvature_midbody_abs_90th']


with PdfPages(figures_dir / 'downsampled_feat_NoComp_30TW_Complied_box_coloured_5slapse.pdf', keep_empty=False) as pdf:
    for feat in tqdm(feats_toplot):
        fig, ax = plt.subplots()
        order = ['0.0', '1.0', '2.0', '3.0', '4.0', '5.0','6.0','7.0','8.0']
        sns.boxplot(x='window_id', y=feat,
                     data=NoComp_30TW_complied_1,
                     order=order)
        ax.set_xticks(np.arange(0, 8, step=1))
        add_stat_annotation(ax, data=NoComp_30TW_complied_1, x='window_id', y=feat,order=order, box_pairs=[("4.0", "5.0"), ("4.0", "6.0")],
                            test='t-test_paired', text_format='full', loc='inside', verbose=2)
        boxes = ax.artists
        for i, box in enumerate(boxes):
            x = NoComp_30TW_complied['window_id'].tolist()[i]
            if x== 1.0 or x== 4.0 or x ==7.0:
                box.set_facecolor('royalblue')
                box.set_edgecolor('black')
            else:
                box.set_facecolor('grey')
                box.set_edgecolor('black')
        pdf.savefig(fig)
        plt.close(fig)

**Comment by DarthTrevis** [comment]
So first, readable code ;) 

```python
feats_toplot = [
    'speed_90th',
    'speed_10th',
    'ang_vel_midbody_abs_90th',
    'd_speed_90th',
    'd_speed_10th',
    'd_ang_vel_midbody_abs_90th',
    'speed_w_forward_90th',
    'speed_w_forward_10th',
    'speed_head_tip_w_forward_90th',
    'speed_head_base_w_forward_90th',
    'speed_tail_base_w_forward_90th',
    'speed_head_tip_w_backward_90th',
    'speed_head_base_w_backward_90th',
    'speed_tail_base_w_backward_90th',
    'quirkiness_50th',
    'width_midbody_50th',
    'motion_mode_paused_frequency',
    'motion_mode_paused_fraction',
    'motion_mode_forward_frequency',
    'motion_mode_forward_fraction',
    'motion_mode_backward_frequency',
    'motion_mode_backward_fraction',
    'curvature_mean_neck_abs_90th',
    'curvature_mean_midbody_abs_90th',
    'd_curvature_midbody_abs_90th'
]

with PdfPages(figures_dir / 'downsampled_feat_NoComp_30TW_Complied_box_coloured_5slapse.pdf',
              keep_empty=False) as pdf:
    for feat in tqdm(feats_toplot):
        fig, ax = plt.subplots()
        order = ['0.0', '1.0', '2.0', '3.0', '4.0', '5.0','6.0','7.0','8.0']
        
        sns.boxplot(x='window_id', y=feat,data=NoComp_30TW_complied_1, 
                    order=order)
                    
        ax.set_xticks(np.arange(0, 8, step=1))
        
        add_stat_annotation(ax, data=NoComp_30TW_complied_1, x='window_id', 
                            y=feat,order=order, 
                            box_pairs=[("4.0", "5.0"), ("4.0", "6.0")],
                            test='t-test_paired', text_format='full', 
                            loc='inside', verbose=2)
        
        boxes = ax.artists
        
        for i, box in enumerate(boxes):
            x = NoComp_30TW_complied['window_id'].tolist()[i]
            
        if x== 1.0 or x== 4.0 or x ==7.0:
            box.set_facecolor('royalblue')
            box.set_edgecolor('black')
            else:
            box.set_facecolor('grey')
            box.set_edgecolor('black')
            pdf.savefig(fig)
            plt.close(fig)
```

Now, what dtype is your `window_id` column ? Because you give strings in `order` and 'box_pairs' but test with integers below.

**Comment by wylhtydtm** [comment]
I am so sorry. I just copied and pasted, and found that the format was messed up after posting.
Name: window_id, dtype: float64

Yup. I think you are right.  At first, I didn't include the order in the code (while keeping the box_pairs as above), it printed out the following error. What should I type in my situation to specify window_id in the order and box_pairs?

  File "<ipython-input-519-422748840e8f>", line 51, in <module>
    test='t-test_paired', text_format='full', loc='inside', verbose=2)

  File "/anaconda3/lib/python3.6/site-packages/statannot/statannot.py", line 460, in add_stat_annotation
    for i in range(len(box_names))]

  File "/anaconda3/lib/python3.6/site-packages/statannot/statannot.py", line 460, in <listcomp>
    for i in range(len(box_names))]

  File "/anaconda3/lib/python3.6/site-packages/statannot/statannot.py", line 326, in get_box_data
    cat = box_plotter.plot_hues is None and boxName or boxName[0]

IndexError: invalid index to scalar variable.

**Comment by DarthTrevis** [comment]
> `I am so sorry. I just copied and pasted, and found that the format was messed up after posting.`

Don't worry, just use this ;) 
\`\`\`python 
[code]
 \`\`\`  

What you could do, before any plotting, is (simplest) to convert your column into `str` with this (or `map` if need to format for `".0"`):
```python
NoComp_30TW_complied_1.window_id = NoComp_30TW_complied_1.window_id.astype(str)
```
You can also transform the series into `Categorical` and then replace categories with the `str` version (If you need to go back to a scalar and cannot/do not wish to make a copy, this is maybe more efficient).

```python
# First with numerical order
order = [_ for _ in range(9)]

NoComp_30TW_complied_1.window_id = pd.Series(pd.Categorical(
    NoComp_30TW_complied_1.window_id, categories=order))

# Then with the str order
order = [str(window_id) for window_id in order]

NoComp_30TW_complied_1.window_id.cat.categories = [
    str(_) for _ in NoComp_30TW_complied_1.window_id.cat.categories]
```

NB: Make sure to specify a format when converting to `str` if do you need the `".0"`.

There may be better solutions but these should work :)

**Comment by wylhtydtm** [comment]
These worked! Thank you very much. Much appreciated!
