### ISSUE TITLE
Hide non-significant annotations

### ISSUE THREAD

**Issue by burtonrj** [webermarcolivier/statannot#50]
This tool is excellent. Thank you for all your hard work. Is it possible to hide non-significant results where multiple comparisons are made? So only show the annotations for significant results?

Thanks!

**Comment by normanius** [comment]
I think you cannot directly. The workaround is to perform the statistical tests yourself and adjust the box-pairs based on the p-values.

```python
# box_pairs: A list of all available box pairs
# pvalues: Dictionary mapping box-pairs to p-values
box_pairs = [ bp for bp in box_pairs if pvalues[bp] < alpha ]
pvalues = [ p for p in pvalues.values() if p < alpha ]
add_stat_annotation(..., pvalues=pvalues, perform_stat_test=False, ...)
```

See [here](https://github.com/webermarcolivier/statannot/blob/master/example/example.ipynb) what is meant by `box_pairs`.

**Comment by normanius** [comment]
Just updated the code...

**Comment by burtonrj** [comment]
Thanks for this, workaround sorted the issue
