### ISSUE TITLE
horizontal orientation

### ISSUE THREAD

**Issue by lacava** [webermarcolivier/statannot#54]
hello, is it possible to use add_stat_annotation with a boxplot that has orient='h'? in other words can the annotations be rotated sideways?

**Comment by huanglau** [comment]
I have written some code and made a pull request with a horizontal plot option #53 . I put some example plots on the request if any of those look like what you're going for.

**Comment by lacava** [comment]
awesome! thank you! i'll check it out.

**Comment by webermarcolivier** [comment]
Now supported in [trevismd/statannotations](https://github.com/trevismd/statannotations).
