### ISSUE TITLE
Multi-comparison adjustment does not automatically apply

### ISSUE THREAD

**Issue by MJuanchich** [webermarcolivier/statannot#56]
I am running three comparisons with an independent t-test and the annotation shows nicely on the plot but the p values are not adjusted following the Bonferroni procedure. I think I have the right statannot version as I have the StatResult.py file in my statannot folder. I am at a loss to find out what the problem is.

When I check the analysis I can see that there is no adjustment as shown below.

Could you help me to "activate" the adjustment? 

`for res in test_results:
    print(res)`

`print("\nStatResult attributes:", test_results[0].__dict__.keys())`

I get:

AxesSubplot(0.125,0.125;0.775x0.755)
[{'pvalue': 1.210296633675592e-07, 'test_short_name': 't-test_ind', 'formatted_output': 't-test independent samples, P_val=1.210e-07 stat=5.397e+00', 'box1': 'Donation? Yes', 'box2': 'Donation? No'}, {'pvalue': 0.002277227049961783, 'test_short_name': 't-test_ind', 'formatted_output': 't-test independent samples, P_val=2.277e-03 stat=-3.074e+00', 'box1': 'Control', 'box2': 'Donation? Yes'}, {'pvalue': 0.003862565144342565, 'test_short_name': 't-test_ind', 'formatted_output': 't-test independent samples, P_val=3.863e-03 stat=2.904e+00', 'box1': 'Control', 'box2': 'Donation? No'}]

**Comment by trevismd** [comment]
Hi,
With bonferonni, pvalues should simply be replaced in the StatResult instance (see [call here](https://github.com/webermarcolivier/statannot/blob/1835078a4e13d896ded8f8fc84c69dbea9393ea8/statannot/statannot.py#L145).)
If you need the original values, you could pass `comparison_correction=None` to your `add_stat_annotation` call (and maybe `verbose=1`to show us both outputs if it doesn't work).

**Comment by MJuanchich** [comment]
Hi trevismd, thanks for answering! I can see from the printout that the correction is not applied as it would say so if it had been. Also, I know from running the analyses in other packages that two of the differences should not be statistically significant after adjustment - whereas they are shown are statistically significant in my figure, hence proving again that the adjustment was not applied... Any idea why this may bet the case? and how to correct it?

**Comment by trevismd** [comment]
Could you show us your code calling `add_stat_annotation` and the text output with `verbose` set to 1? (Or a minimal example showing the problem)

Without that, I can only imagine that the reason is one of two things:
- you are not "summoning" a test within `statannot` but providing pvalues, in which case `statannot` does not apply corrections. (An new issue for a new feature may be the solution if you'd like that).
- There is a genuine bug somewhere.

**Comment by MJuanchich** [comment]
Here is my code:

`with sns.plotting_context("notebook", font_scale=1.4):` 
   ` x = "IV_MAIN_Variable"`
    `y = "Diff_T2_PositiveMood_PostminusPre"`
    `order = ["Control","Donation? Yes", "Donation? No"]`
    `ax = sns.boxplot(data=df_long, x=x, y=y, order=order, showmeans=True, palette= col3,`
                     `meanprops={"marker":"s","markerfacecolor":"white", "markeredgecolor":"black"})`
    `test_results = add_stat_annotation(ax, data=df_long, x=x, y=y, order=order,`
                                   `box_pairs=[("Donation? Yes", "Donation? No"),("Control","Donation? Yes"),` `("Control","Donation? No")],`
                                   `test='t-test_ind', text_format='star', loc='outside', verbose=1)`
`plt.xlabel('') `
`plt.ylabel('Effect of request on happiness') `

this is what is shows (where ** should actually be ns):

![image](https://user-images.githubusercontent.com/49307923/93097541-a19de780-f69d-11ea-85b2-1ed537eba79b.png)

**Comment by trevismd** [comment]
I cannot see how this happens if the right package version is correctly installed in the kernel's environment. (Which you can check with `statannot.__version__` in a notebook cell.)
If it is indeed installed and loaded, in order to discern between the missing feature or the missing use of it as default, could you add the argument `comparisons_correction="bonferonni"`  ? Thanks

**Comment by MJuanchich** [comment]
The .__version__ code does not seem to work with statannot, as I get an error message as shown below:

`statannot.__version__`

AttributeError: module 'statannot.statannot' has no attribute '__version__'

Thanks for your help!

If I run the plot code above while specifying that I want the p values to be adjusted by adding `comparisons_correction="bonferonni"` , then I have an error message as follows: 

TypeError: add_stat_annotation() got an unexpected keyword argument 'comparisons_correction'

**Comment by trevismd** [comment]
> If I run the plot code above while specifying that I want the p values to be adjusted by adding comparisons_correction="bonferonni" , then I have an error message as follows:
> 
> TypeError: add_stat_annotation() got an unexpected keyword argument 'comparisons_correction'

This is really in favor of the function not having the right interface, so it is not the latest version.
I'd try running `pip install -u statannot` (or `pip install .` from the git repository you locally have downloaded) from a console in the right environment.

> AttributeError: module 'statannot.statannot' has no attribute 'version'

This behavior is also curious. Did you include the two `_` on each side of `version` in `.__version__`?

Hope it will indeed help

**Comment by MJuanchich** [comment]
When I look at the package using pip freeze, I get that it is the 0.2.2. - isn't that the one with the automatic use of correction?

I have replicated the issue with data form the pokemon file

`with sns.plotting_context("notebook", font_scale=1.4):  `
   ` x = "Type 1"`
   ` y = "Attack"`
    `order = ["Grass", "Fire", "Water"]`
    `ax = sns.boxplot(data=df, x=x, y=y, showmeans=True, `
                     `meanprops={"marker":"s","markerfacecolor":"white", "markeredgecolor":"black"})`
    `test_results = add_stat_annotation(ax, data=df, x=x, y=y,order=order,`
                                   `test='t-test_ind', text_format='star', loc='outside', verbose=1,`
                                  ` box_pairs=[("Grass", "Fire"),("Fire","Water"), ("Grass","Water")])`

**Comment by MJuanchich** [comment]
and I used the two __ - and it worked to get the version of seaborn for example - but not for the version of statannot...

**Comment by MJuanchich** [comment]
here is the output using the pokemon file. It does not mention the bonferroni adjustment (nor does it use it).

Grass v.s. Fire: t-test independent samples, P_val=1.702e-01 stat=-1.418e+00
Fire v.s. Water: t-test independent samples, P_val=1.321e-01 stat=1.539e+00
Grass v.s. Water: t-test independent samples, P_val=9.609e-01 stat=4.932e-02

**Comment by trevismd** [comment]
I just saw that 0.2.2 was the version before, created on jan 22 in `_version.py` that was not updated in the latest 0.2.3 github tag and Pypi 0.2.3 package.
So while this information is not useful to identify your problem, it did reveal that; 

That said, you do not have the latest version installed as pip freeze should have given you `statannot==0.2.3` (just tested it)

**Comment by MJuanchich** [comment]
Hi Trevis, How can I get the latest version of statannot? Even if I reinstall it through gitub I still have the old version (and on the main page, the version is indeed the old one)... Is there any way I can upgrade it?

**Comment by MJuanchich** [comment]
here is how it looks like when I download what is supposed to be the 0.2.3. version:

![image](https://user-images.githubusercontent.com/49307923/93329992-fa908b80-f815-11ea-885a-e383da6ad41a.png)

**Comment by trevismd** [comment]
It is not shown in that file, but latest is 0.2.3, as shown in the address bar of your last screenshot.
Does the function still not work ? 

If it doesn't, I'd try `pip install --upgrade --no-deps --force-reinstall statannot`, and restart the jupyter kernel.

**Comment by MJuanchich** [comment]
I tried the upgrade as you described but did not work. I get the following error message:

![image](https://user-images.githubusercontent.com/49307923/93334692-42ff7780-f81d-11ea-9a16-79724d2d4890.png)


I tried to reinstall the package from the beginning after deleting all the relevant folders, and it works but it still seems I have the wrong version installed: 
![image](https://user-images.githubusercontent.com/49307923/93334493-f0be5680-f81c-11ea-9658-62a67766a573.png)

and the adjustment is not applied when I run the figures:

![image](https://user-images.githubusercontent.com/49307923/93334568-0b90cb00-f81d-11ea-89cf-4d68b90eec94.png)

**Comment by trevismd** [comment]
I can provide one last recommendation, but if it does not work, I think you should check out stackoverflow or google for a general explanation as to why you're experiencing this. There is something wrong with your system rather then statannot's code.

Try to forget the github code at the moment, and from *another directory* run
```bash
$ pip uninstall statannot
# And then,
$ pip install statannot 
```

Hope it helps. I don't know if something may be/have been corrupted after manual changes...

**Comment by MJuanchich** [comment]
I finally managed to get the latest version of the package, but still the bonferroni adjustment does not show on the plot... Thank for all your help Trevismd!

![image](https://user-images.githubusercontent.com/49307923/93489110-073cde80-f8ff-11ea-9d85-dadabf3a1932.png)

**Comment by trevismd** [comment]
You can finally check that the same environment is used in jupyter entering this in a cell;
```
!pip freeze
```
Then if you still get 0.2.3, 
> [...], in order to discern between the missing feature or the missing use of it as default, could you > add the argument comparisons_correction="bonferonni" ?

**Comment by MJuanchich** [comment]
arg so annoying - I don't understand why, the versaion shown there is the statannot 0.2.1... :/ Via the cmd environment I see that I have the 0.2.3. but not here... It seems my jupyter document does not rely on the same version? So sorry it is such a mess...

statannot==0.2.1
![image](https://user-images.githubusercontent.com/49307923/93578819-b0361880-f995-11ea-89db-9b4fd03da771.png)

**Comment by trevismd** [comment]
Seems you would be working from a conda environment with jupyter. 
You can - launch "Anaconda prompt" instead of a regular cmd to have the conda command available and activate the env.
Or you can either launch a terminal from jupyter with the "New" button and use that to update statannot.
![help](https://user-images.githubusercontent.com/477844/93611002-0757df80-f9ce-11ea-9864-b07fe534f6ba.png)
Good luck!
