### ISSUE TITLE
Something in between full and simple

### ISSUE THREAD

**Issue by johngillece** [webermarcolivier/statannot#60]
I was writing to ask the easiest way to get the absolute p-value without also printing the type of test utilized (i.e. text_format = full). Essentially, I want to the "simple" output, but with the actual p-value not the simplified form (e.g. <0.05

**Comment by trevismd** [comment]
Hi @johngillece , 

Have you tried passing `pvalue_thresholds=[]` with `text_format='simple'` to your `add_statannotation` call?
