### ISSUE TITLE
annotations in a straight line

### ISSUE THREAD

**Issue by garincle** [webermarcolivier/statannot#64]
Hello, 
I would like to know if there is a way to have all annotations in a straight line.
When there is a lot of boxes it doesn't leave a lot of space for the results. However, I can't find a way to have all the annotations in a straight line.
Thank you!
Clément

**Comment by garincle** [comment]
hello, 
sorry If my question was not clear? 
The idea is to have a result that looks like that:
![vnxvnj](https://user-images.githubusercontent.com/33903508/114628873-9cca0200-9c85-11eb-9068-3b316a4ab9ca.png)

instate of that:
![Old_VS_Middle-aged_all_CEST005_lemur](https://user-images.githubusercontent.com/33903508/114628757-63919200-9c85-11eb-9002-b0b15d7d49b1.png)

That could really help!
Thank you!

**Comment by garincle** [comment]
or in a straight line at the top, that would be ideal!

**Comment by webermarcolivier** [comment]
Already supported in `statannot`. See also [trevismd/statannotations](https://github.com/trevismd/statannotations).
