### ISSUE TITLE
Is there a one-side ind or welch t-test ?

### ISSUE THREAD

**Issue by hfl112** [webermarcolivier/statannot#68]
I saw found the feature only in Mann-Whitney. but there is no one-side t-test ?

**Comment by trevismd** [comment]
It is not provided as a shortcut but you can add `stats_params={'alternative': 'less'}` (or `greater`) to your call to `add_stat_annotation`, this will be passed to `scipy.stats.ttest_ind` to do what you need.

**Comment by webermarcolivier** [comment]
Move discussion to [trevismd/statannotations](https://github.com/trevismd/statannotations).
