### ISSUE TITLE
ValueError: boxPairList contains an unvalid box pair.

### ISSUE THREAD

**Issue by prubbens** [webermarcolivier/statannot#7]
When trying to visualize statistical significance between two boxplots, plotted by making use of the `hue` variable, I get the following error: 

     ValueError: boxPairList contains an unvalid box pair.

When printing the `.group_names` or `.hue_names` of the `BoxPlotter` object, nothing is returned, which is probably causing the error. 

Any ideas on how to solve this?

**Comment by webermarcolivier** [comment]
This might depends on the type of data of the hue column. Which type does it have? Could you post a minimal example?

**Comment by prubbens** [comment]
Data of hue column is integer. However, column names are also empty, which are strings.

**Comment by webermarcolivier** [comment]
I cannot reproduce this behavior in seaborn 0.9.0. Are all column names empty? Then how do you pass x and y arguments in seaborn boxplot method?

**Comment by prubbens** [comment]
Working example: 

     import numpy as np
     import pandas as pd
     import seaborn as sns
     from statannot import add_stat_annotation

     a = np.zeros(50)
     b = np.ones(50)
     status = np.concatenate((a,b), axis=None)
     values = np.random.rand(100)
     df = pd.DataFrame({'status':status,'values':values})
     df['Category'] = 'Category'
     g = sns.boxplot(x='Category', y='values', hue='status', data=df)#, kind='box')
     add_stat_annotation(g, data=df, x='Category', y='status',
                    boxPairList=[(('Category', '0'), ('Category', '1'))],
                    test='Mann-Whitney', textFormat='star', loc='outside', verbose=2)

**Comment by prubbens** [comment]
Thanks, this fixed it.
