### ISSUE TITLE
Barplot error bars?

### ISSUE THREAD

**Issue by Sarah335** [webermarcolivier/statannot#71]
Do the errors bars on the barplot represent standard deviation or standard error? Neither of which seems to correspond to these values for my data.

**Comment by trevismd** [comment]
They are confidence intervals calculated by bootstrapping, but you can switch that to standard deviation. See seaborn's documentation here [https://seaborn.pydata.org/generated/seaborn.barplot.html](https://seaborn.pydata.org/generated/seaborn.barplot.html).
