### ISSUE TITLE
is it possible to remove the "ns" label but only keep the significant symbol?

### ISSUE THREAD

**Issue by XiaoqiongGu** [webermarcolivier/statannot#74]
Hi, 

Thank you so much for making this wonderful plugin and it helps me a lot in my research.

I have one request and wondering if you would like to improve in your future plans. 
for some cases, we may only wanna **keep the significant symbols while removing all the "ns" labels**. 
I checked somehow it is not implemented in the current version, wondering is it possible to realize it in the near future?

but again, just small advice, and thanks a lot for your contributions already!
shirley

**Comment by ravikiranrao** [comment]
@XiaoqiongGu Did you get anything in this direction? I am also lookout for this feature. Thanks.

**Comment by XiaoqiongGu** [comment]
> feature

Unfortunately, this feature has not been added to the system. So I exported and removed "ns" in the adobe illustrator...

**Comment by webermarcolivier** [comment]
New feature requests should be posted to [trevismd/statannotations](https://github.com/trevismd/statannotations).
