### ISSUE TITLE
Barplot with hue

### ISSUE THREAD

**Issue by gm039** [webermarcolivier/statannot#75]
Hi,

I want to generate a plot similar to this. Where can I find the script? Please help me.
![example_hue_pairs](https://user-images.githubusercontent.com/50217085/118265077-b0d07180-b486-11eb-9fe2-830f1d7e5559.png)

Thanks

**Comment by trevismd** [comment]
There are several in the example notebook, like cell [28] in `Boxplot with hue`.
See https://github.com/webermarcolivier/statannot/blob/9b9c6c44/example/example.ipynb
