### ISSUE TITLE
RuntimeError : Cannot get window extent w/o renderer

### ISSUE THREAD

**Issue by theorible** [webermarcolivier/statannot#8]
Hey there !
I'm having a RuntimeError running this : 
```python
data
Out[66]: 
    Control    FBS 1%    FBS 3%
0  0.494348  1.196539  0.921887
1  0.556027  0.940206  1.153515
2  0.445540       NaN  1.108820
3  0.464731  0.931461  0.956742
4  0.393526  0.894547  1.073090
5  0.479290       NaN  1.099829
6  0.683442  0.936075       NaN
7  0.667166       NaN       NaN
8  0.526530       NaN       NaN
9  0.499731       NaN       NaN

statannot.add_stat_annotation(ax, data, boxPairList=[('Control','FBS 1%'), ('Control','FBS 3%'), ('FBS 1%','FBS 3%')], test='t-test', textFormat='star',loc='outside', verbose=1)

pvalue annotation legend:
ns: 5.00e-02 < p <= 1.00e+09
*: 1.00e-02 < p <= 5.00e-02
**: 1.00e-03 < p <= 1.00e-02
***: 1.00e-04 < p <= 1.00e-03
****: p <= 1.00e-04

Traceback (most recent call last):

  File "<ipython-input-67-57fb82b05cc8>", line 1, in <module>
    statannot.add_stat_annotation(ax, data, boxPairList=[('Control','FBS 1%'), ('Control','FBS 3%'), ('FBS 1%','FBS 3%')], test='t-test', textFormat='star',loc='outside', verbose=1)

  File "C:\Users\analysesbiophysique\.spyder-py3\projets\Imaging\packages\statannot.py", line 218, in add_stat_annotation
    bbox = ann.get_window_extent()

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\text.py", line 2323, in get_window_extent
    text_bbox = Text.get_window_extent(self, renderer=renderer)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\text.py", line 920, in get_window_extent
    raise RuntimeError('Cannot get window extent w/o renderer')

RuntimeError: Cannot get window extent w/o renderer
```

Do you have any idea why this is happenning ?

Thanks !

**Comment by theorible** [comment]
Thanks for your quick answer.
I tried your code and still get the same error. It still starts to plot :
![figure_1](https://user-images.githubusercontent.com/45488538/49292863-b7cdba00-f4ae-11e8-9c23-ccaf653633d2.png)


Error must happen when it tries to do the second test stat or bar.

I am under matplotlib 2.2.3, I read some issues about the same error happening in other situations and it looks like it's related to matplotlib version. Although I didn't understand everything.

**Comment by webermarcolivier** [comment]
I have implemented a fallback solution upon this kind of error, using a fixed offset (8196cb39e127e0c24e59640b66cca8db0b8bd886). Could you try it?

**Comment by theorible** [comment]
No error raised this time but the different bars are at the same level : 
![figure_1-1](https://user-images.githubusercontent.com/45488538/49298971-ece20880-f4be-11e8-8a68-780c57109fde.png)

**Comment by theorible** [comment]
No, I only have the pvalue legend in return.

**Comment by webermarcolivier** [comment]
Could you test the test branch?

**Comment by theorible** [comment]
I think everything is working pretty well. I am working on spyder and when I set my output plot into interpreter I get the good graph :
￼
![image](https://user-images.githubusercontent.com/45488538/49305125-a4cae200-f4ce-11e8-8985-919430de21b6.png)

But when I set parameter to have it in an other window it gives me the same graph as before. I think there might be a compatibility problem with that kind of settings !

Thank you for your answers anyway, I guess I will be able to manage it from now. Maybe you can explore this compatibility problem.

**Comment by ngjiansheng** [comment]
Hi, it is possible to just show the statistical significant bars and omit the 'ns'?

**Comment by webermarcolivier** [comment]
Please open a new issue for this question.
Yes you can give custom pvalue thresholds and annotation texts, and use an empty string when the pvalue is between 0.05 and 1,
```python
pvalue_thresholds=[[1e-4, "****"], [1e-3, "***"], [1e-2, "**"], [0.05, "*"], [1, ""]]
```
