### ISSUE TITLE
"loc=outside" causes significance annotations to be cut out of the plot

### ISSUE THREAD

**Issue by saskra** [webermarcolivier/statannot#80]
Example:
![violin_out](https://user-images.githubusercontent.com/12963485/124238231-99be0f80-db18-11eb-83b8-fe3c2a9ca0b0.png)

Code:
```python
sns.set_style('ticks')
ax = sns.violinplot(data=df_jpi, inner=None, color=".8")
sns.stripplot(data=df_jpi)
# ax.set(ylim=(0, 1))
test_results = add_stat_annotation(ax, 
                                                      data=df_jpi, 
                                                      box_pairs=[("X", "Y"), ("X", "Z"), ("Y", "Z")], 
                                                      test='Mann-Whitney', 
                                                      text_format='star', 
                                                      loc='outside', 
                                                      verbose=2)
fig = ax.get_figure()
fig.savefig('violin_out.png', transparent=True)
fig.show()

```

This does not happen with "loc=inside".

**Comment by trevismd** [comment]
Could you provide a small dataset to explore this ?

**Comment by saskra** [comment]
It does not depend on the dataset, so you can just use random data like these:

```python
df_jpi = pd.DataFrame(np.random.randint(0, 100, size=(100, 3)), columns=list('XYZ'))
```

**Comment by trevismd** [comment]
You can use 
```python
fig.tight_layout()
```
to resize the figure to the added content before calling `plt.show()`.  
This is done with the parameter `bbox_inches='tight'` when saving the image (such as in the example notebook), but for `plt.show()`, this is the function to call first. 

Thanks for reporting this. I'll look into automatically performing this step after adding annotations outside the plotting area (in `statannotations`).

**Comment by saskra** [comment]
Thanks a lot!
