### ISSUE TITLE
statannot on seaborn.catplot with columns/rows

### ISSUE THREAD

**Issue by okushnir** [webermarcolivier/statannot#82]
Hi,
Could you please add a feature to add_stat_annotation so it will work on seaborn.catplot with columns/rows?
![catplot_col](https://user-images.githubusercontent.com/29273932/127970603-0819d548-04a9-4a73-8183-b68cae04986a.png)

**Comment by webermarcolivier** [comment]
Implemented in [trevismd/statannotations](https://github.com/trevismd/statannotations).
